name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on:
  issue_comment:

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '!actions mirror' || github.event.comment.body == '!actions run all' }}
    steps:
      - uses: actions/checkout@v2
      - name: Mirror Repository
        run: |
          git config --global init.defaultBranch "main"
          git config --global user.email "hardliner66@gmail.com"
          git config --global user.name "hardliner66"
          echo "Removing old git history..."
          rm -rf .git .gitmodules extern
          echo "Reinitializing repository..."
          git init
          git submodule add https://github.com/cameron314/concurrentqueue extern/concurrentqueue
          git submodule add https://github.com/Hejsil/zig-clap extern/zig-clap
          git submodule add https://github.com/zig-gamedev/zig-gamedev extern/zig-gamedev
          mv README.md README_OLD.md
          echo "# THIS IS A MIRROR OF A PRIVATE REPO" > README.md
          echo "" >> README.md
          cat README_OLD.md >> README.md
          rm README_OLD.md
          git add .
          git commit -m "MIRROR"
          echo "Force pushing to target repository..."
          git remote add origin https://github.com/hardliner66/abps.git
          echo "Using access token for authentication..."
          git push -u https://${GH_USERNAME}:${GH_TOKEN}@github.com/hardliner66/abps.git main --force
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
