name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on:
  push:
  schedule:
    - cron: "@daily"

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mirror Repository
        run: |
          git config --global init.defaultBranch "main"
          git config --global user.email "hardliner66@gmail.com"
          git config --global user.name "hardliner66"
          echo "Removing old git history..."
          rm -rf .git .gitmodules extern
          echo "Reinitializing repository..."
          git init
          git submodule add https://github.com/cameron314/concurrentqueue extern/concurrentqueue
          git add .
          git commit -m "MIRROR"
          echo "Force pushing to target repository..."
          git remote add origin https://github.com/hardliner66/abps.git
          echo "Using access token for authentication..."
          git push -u https://${GH_USERNAME}:${GH_TOKEN}@github.com/hardliner66/abps.git main --force
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
